import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  fetchCard,
} from "../redux/reducers/cardReducer";

const Home: NextPage = () => {

  const dispatch = useDispatch();
  const { cards } = useSelector(
    (state) => state.card
  );

  useEffect(() => {
    dispatch(fetchCard());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.grid}>
          {
            cards ? cards.map((card: any) => (
              <div key={card.id}>
                <img src={card.img} alt={card.name} />
              </div>
            ))
              : <div>loading...</div>
          }
        </div>
      </main>
    </div>
  )
}

export default Home